# Generated by Django 2.2.4 on 2019-08-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_availability',
            field=models.BooleanField(),
        ),
    ]
