# Generated by Django 2.2.5 on 2019-09-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190830_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
