# Generated by Django 2.2.5 on 2019-09-13 17:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_car_car_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start_date', models.DateField(default=datetime.datetime(2019, 9, 13, 17, 58, 21, 90713), verbose_name='rental_date')),
                ('rental_due_date', models.DateField(default=datetime.datetime(2019, 9, 14, 17, 58, 21, 90713), verbose_name='rental_date')),
                ('rental_car', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Car')),
                ('rental_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
